### ISSUE TITLE
handling of enum abstract

### ISSUE THREAD

**Issue by AlexHaxe** [jdonaldson/paths#1]
Current enum abstract handling feels wrong: with `path.parse("Foo/Boo/100"))` you get `Foo(hooo, 100)`, whereas `path.parse("Foo/hooo/100"))` produces `Uncaught exception error.InvalidParse`.

I would expect that enum abstract field names should be what you use in your code (design time), and use their values at runtime (that's how enum abstracts normally work, being something that only lives during design and compiletime). 
So incoming and generated paths should contain values not field names, because they are unknown to the outside.

**Comment by jdonaldson** [comment]
I agree in principal, and had it functioning this way at first. 

What changed my mind is that I wanted to have consistent alias metadata for both abstract/classic enums:

e.g.:

```haxe
enum Foo {
  @:alias("bar-path")
  Bar
}
```
and

```haxe
abstract enum Foo {
  @:alias("bar-path")
   var Bar = "bar"
}
```

The path for these would be `/Foo/bar-path`, although they would resolve to different run time values.

The benefit is that the `@:alias` metadata would consistently handle the input translation for the path, while the abstract value could function as an output translation (to another value).

I thought this would give the developer the most (consistent) control.

**Comment by AlexHaxe** [comment]
I find using `@:alias` on an enum abstract a bit confusing, because `var Bar = "bar"` already is an alias. Adding alias metadata would give you two ways to define aliases. 
Either way I would expect `Foo/bar/1` to yield in `Foo(Bar, 1)` when there is no metadata, and in case of an `@:alias` metadata it should be `Foo/bar-path/1` that also returns `Foo(Bar, 1)`. In both cases I wouldn't expect `Foo/Bar/1` to work.

Current version of `toPath(Foo(Baz,1))` produces correct(imho) result `Foo/heeey/1` instead of `Foo/Baz/1` (with alias it should be something like `Foo/baz-path/1`).

I agree that for regular enums aliases are necassary, because `@:alias` allows you to specify text representations, especially when you want to use characters not allowed in enum fields.

**Comment by jdonaldson** [comment]
How should non-string abstracts work then?

E.g.:

```haxe
abstract enum Foo {
  var Bar = 1;
}
```

**Comment by jdonaldson** [comment]
Those could be converted from their base type I suppose.

**Comment by AlexHaxe** [comment]
I think it makes sense to only support enum abstracts based on strings and numbers. They are probably also the most common ones. 
I mean you usually use an enum abstract because you need a set of constant values which trigger warnings when a case is missing from your switches.

**Comment by jdonaldson** [comment]
I see how this all makes sense in terms of "principle of least surprise".  I'll change the behavior back.  I'll also add some tests.
